### ISSUE TITLE
Create homework assignment

### ISSUE THREAD

**Issue by jbride** [redhat-gpe/bxms_ci_cd#1]
Homework assignment is executed by student after completion of first week on-site ILT with GPTE instructor as part of _advanced_ proficiency of _automation_ learning path.

Not exactly sure this homework assignment could be designed / implemented in such a manner that the testing / validation of the assignment could be automated.  Need to brainstorm ideas.

**Comment by abhaskar** [comment]
Don't forget that we have access to hackerrank... it may be an option.
